name: inv
services:

  peer1:
    container_name: peer1
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=1
    volumes:
      - ./config.yaml:/config.yaml


  peer2:
    container_name: peer2
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=2
    volumes:
      - ./config.yaml:/config.yaml


  peer3:
    container_name: peer3
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=3
    volumes:
      - ./config.yaml:/config.yaml


  peer4:
    container_name: peer4
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=4
    volumes:
      - ./config.yaml:/config.yaml


  peer5:
    container_name: peer5
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=5
    volumes:
      - ./config.yaml:/config.yaml


  peer6:
    container_name: peer6
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=6
    volumes:
      - ./config.yaml:/config.yaml


  peer7:
    container_name: peer7
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=7
    volumes:
      - ./config.yaml:/config.yaml


  peer8:
    container_name: peer8
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=8
    volumes:
      - ./config.yaml:/config.yaml


  peer9:
    container_name: peer9
    image: invitation:latest
    entrypoint: /invitation
    networks:
      - testing_net
    environment:
      - INV_NAME=9
    volumes:
      - ./config.yaml:/config.yaml


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24